AWSTemplateFormatVersion: '2010-09-09'
Description: Private Certificate Provider
Parameters:
  S3BucketPrefix:
    Type: String
    Default: ''
  CFNCustomProviderZipFileName:
    Type: String
    Default: lambdas/cfn-private-certificate-provider-latest.zip
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: CFNPrivateCertificateAuthorityProvider
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/certauth/*'
              - Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
                Effect: Allow
  CFNCustomProvider:
    Type: AWS::Lambda::Function
    Properties:
      Description: Custom CloudFormation Provider implementation
      Code:
        S3Bucket: !Sub '${S3BucketPrefix}-${AWS::Region}'
        S3Key: !Ref 'CFNCustomProviderZipFileName'
      FunctionName: cfn-private-certificate-provider
      Handler: provider.handler
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Timeout: 300
      Runtime: python3.7
