AWSTemplateFormatVersion: '2010-09-09'
Description: Custom Private Root Certificate Provider
Resources:
  RootCA:
    Type: Custom::PrivateRootCertificate
    Properties:
      CAName: my-private-ca
      RefreshOnUpdate: true
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-private-certificate-provider'

  Server01Certificate:
    Type: Custom::PrivateCertificate
    Properties:
      CAName: !GetAtt RootCA.CAName
      Hostname: 'server01.local'
      RefreshOnUpdate: true
      Version: !GetAtt RootCA.Hash
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-private-certificate-provider'

  Server02Certificate:
    Type: Custom::PrivateCertificate
    Properties:
      CAName: !GetAtt RootCA.CAName
      Hostname: 'server02.local'
      RefreshOnUpdate: true
      Version: !GetAtt RootCA.Hash
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-private-certificate-provider'

Outputs:
  RootCAPublicKey:
    Description: public key of the root CA
    Value: !GetAtt 'RootCA.PublicCertPEM'

  Server01PublicKey:
    Description: public key of server01
    Value: !GetAtt 'Server01Certificate.PublicCertPEM'

  Server02PublicKey:
    Description: public key of server02
    Value: !GetAtt 'Server02Certificate.PublicCertPEM'
